/**
 * eslint-disable @sap/ui5-jsdocs/no-jsdoc
 */

sap.ui.define([
        "sap/ui/core/UIComponent",
        "sap/ui/Device",
        "afs/aplicacion/model/models"
    ],
    function (UIComponent, Device, models) {
        "use strict";

        return UIComponent.extend("afs.aplicacion.Component", {
            metadata: {
                manifest: "json"
            },

            /**
             * The component is initialized by UI5 automatically during the startup of the app and calls the init method once.
             * @public
             * @override
             */
            init: function () {
                // call the base component's init function
                UIComponent.prototype.init.apply(this, arguments);

                // enable routing
                this.getRouter().initialize();

                // set the device model
                this.setModel(models.createDeviceModel(), "device");
                var oData = {
                    "tab3table01":[{"id":""}],
                    "tab3table01Data":[
                        {"estado":"Check", "fecha":"01/10/2022","protocolo":"Protocolo de revisión","detalle":"Quemadura dorsal"},
                        {"estado":"Check", "fecha":"03/10/2022","protocolo":"Protocolo de revisión","detalle":"Insuficiencia respitaroria"}
                    ],
                    "table01": [
                        {"key":"key0","desc":"HERIDAS PUNZANTES"},
                        {"key":"1","desc":"Microempresa"},
                        {"key":"2","desc":"Pequeña Empresa"},
                        {"key":"3","desc":"Mediana Empresa"},
                        {"key":"4","desc":"Gran Empresa"},
                        {"key":"5","desc":"Instituciones del Estado"},
                        {"key":"6","desc":"Mineria Artesanal"},
                        {"key":"7","desc":"Pequeña Mineria"},
                        {"key":"8","desc":"Mediana y Gran Mineria"}
                        ],
                        
                    "table02":[
                        {"key":"key0","desc":"ENFERMEDADES PROFESIONALES CAUSADAS POR AGENTES FÍSICOS"},
                        {"key":"A","desc":"Agricultura"},
                        {"key":"B","desc":"Pesca"},
                        {"key":"C","desc":"Minas y Canteras"},
                        {"key":"D","desc":"Manufactura"},
                        {"key":"E","desc":"Electricidad, Gas y Agua"},
                        {"key":"F","desc":"Construccion"},
                        {"key":"G","desc":"Comercio"},
                        {"key":"H","desc":"Hoteles y Restaurantes"},
                        {"key":"I","desc":"Transporte, Almacenamiento y Comunicaciones"},
                        {"key":"J","desc":"Intermediacion Financiera"},
                        {"key":"K","desc":"Activ. Inmob. Empresarial"},
                        {"key":"L","desc":"Administracion Poblica y Defensa"},
                        {"key":"M","desc":"Enseñanza"},
                        {"key":"N","desc":"Servicios Sociales y de Salud"},
                        {"key":"O","desc":"Servicios"}
                        ],
                    "table03":[
                        {"key":"1","desc":"Funcionario"},
                        {"key":"2","desc":"Empleado"},
                        {"key":"3","desc":"Jefe de Planta"},
                        {"key":"4","desc":"Capataz"},
                        {"key":"5","desc":"Tecnico"},
                        {"key":"6","desc":"Operario"},
                        {"key":"7","desc":"Oficial"},
                        {"key":"8","desc":"Peon"},
                        {"key":"9","desc":"Otros"}
                        ],
                        
                    "table04":[
                        {"key":"1","desc":"Caidas de personas"},
                        {"key":"11","desc":"Caidas de personas con desnivelacion [Caidas desde alturas (arboles, edificios, andamios, escaleras, maquinas de trabajo, vehiculos) y en profundidades (pozos, fosos, excavaciones, aberturas en el suelo)]"},
                        {"key":"12","desc":"Caidas de personas que ocurren al mismo nivel"},
                        {"key":"2","desc":"Caidas de objetos"},
                        {"key":"21","desc":"Derrumbe (Caidas de masas de tierra, de rocas, de piedras, de nieve)"},
                        {"key":"22","desc":"Desplome (de edificios, de muros, de andamios, de escaleras, de pilas de mercancias)"},
                        {"key":"23","desc":"Caidas de objetos en curso de manutencion manual"},
                        {"key":"24","desc":"Otras Caidas de objetos"},
                        {"key":"3","desc":"Pisadas sobre, choques contra, o golpes por objetos, a excepcion de Caidas de objetos"},
                        {"key":"31","desc":"Pisadas sobre objetos"},
                        {"key":"32","desc":"Choques contra objetos inmoviles (a excepcion de choques debidos a una caida anterior)"},
                        {"key":"33","desc":"Choque contra objetos moviles"},
                        {"key":"34","desc":"Golpes por objetos moviles (comprendidos los fragmentos volantes y las particulas), a excepcion de los golpes por objetos que caen"},
                        {"key":"4","desc":"Atrapada por un objeto o entre objetos"},
                        {"key":"41","desc":"Atrapada por un objeto"},
                        {"key":"42","desc":"Atrapada entre un objeto inmovil y un objeto movil"},
                        {"key":"43","desc":"Atrapada entre dos objetos moviles (a excepcion de los objetos volantes o que caen)"},
                        {"key":"5","desc":"Esfuerzos excesivos o falsos movimientos"},
                        {"key":"51","desc":"Esfuerzos fisicos excesivos al levantar objetos"},
                        {"key":"52","desc":"Esfuerzos fisicos excesivos al empujar objetos o tirar de ellos"},
                        {"key":"53","desc":"Esfuerzos fisicos excesivos al manejar o lanzar objetos"},
                        {"key":"54","desc":"Falsos movimientos"},
                        {"key":"6","desc":"Exposicion a, o contacto con, temperaturas extremas"},
                        {"key":"61","desc":"Exposicion al calor (de la atmosfera o del ambiente de trabajo)"},
                        {"key":"62","desc":"Exposicion al frio (de la atmosfera o del ambiente de trabajo)"},
                        {"key":"63","desc":"Contacto con sustancias u objetos ardientes"},
                        {"key":"64","desc":"Contacto con sustancias u objetos muy frios"},
                        {"key":"7","desc":"Exposicion a, o contacto con, la corriente electrica"},
                        {"key":"8","desc":"Exposicion a, o contacto con, sustancias nocivas o radiaciones"},
                        {"key":"81","desc":"Contacto por inhalacion, por ingestion o por absorcion con sustancias nocivas"},
                        {"key":"82","desc":"Exposicion a radiaciones ionizantes"},
                        {"key":"83","desc":"Exposicion a otras radiaciones"},
                        {"key":"9","desc":"Otras formas de accidente, no clasificadas bajo otros epigrafes, incluidos aquellos accidentes no clasificados por falta de datos suficientes"}
                        ],
                        
                    "table05":[
                        {"key":"11","desc":"11 Generadores de energia, excepto motores electricos:"},
                        {"key":"111","desc":"111 Maquinas de vapor"},
                        {"key":"112","desc":"112 Maquinas de combustion interna"},
                        {"key":"119","desc":"119 Otros"},
                        {"key":"12","desc":"12 Sistemas de transmision:"},
                        {"key":"121","desc":"121 Arboles de transmision"},
                        {"key":"122","desc":"122 Correas, cables, poleas, cadenas, engranajes"},
                        {"key":"129","desc":"129 Otros"},
                        {"key":"13","desc":"13 Maquinas para el trabajo del metal:"},
                        {"key":"131","desc":"131 Prensas mecanicas"},
                        {"key":"132","desc":"132 Tomos"},
                        {"key":"133","desc":"133 Fresadoras"},
                        {"key":"134","desc":"134 Rectificadoras y muelas"},
                        {"key":"135","desc":"135 Cizallas"},
                        {"key":"136","desc":"136 Forjadoras"},
                        {"key":"137","desc":"137 Laminadoras"},
                        {"key":"139","desc":"139 Otras"},
                        {"key":"14","desc":"14 Maquinas para trabajar la madera y otras materias similares:"},
                        {"key":"141","desc":"141 Sierras circulares"},
                        {"key":"142","desc":"142 Otras sierras"},
                        {"key":"143","desc":"143 Maquinas de moldurar"},
                        {"key":"144","desc":"144 Cepilladoras"},
                        {"key":"149","desc":"149 Otras"},
                        {"key":"15","desc":"15 Maquinas agricolas:"},
                        {"key":"151","desc":"151 Segadoras, incluso segadoras-trilladoras"},
                        {"key":"152","desc":"152 Trilladoras"},
                        {"key":"159","desc":"159 Otras"},
                        {"key":"16","desc":"16 Maquinas para el trabajo en las minas"},
                        {"key":"161","desc":"161 Maquinas de rozar"},
                        {"key":"169","desc":"169 Otras"},
                        {"key":"19","desc":"19 Otras maquinas no clasificadas bajo otros epigrafes:"},
                        {"key":"191","desc":"191 Maquinas para desmontes, excavaciones, etc., a excepcion de los medios de transporte"},
                        {"key":"192","desc":"192 Maquinas de hilar, de tejer y otras maquinas para la industria textil"},
                        {"key":"193","desc":"193 Maquinas para la manufactura de productos alimenticios y bebidas"},
                        {"key":"194","desc":"194 Maquinas para la fabricacion del papel"},
                        {"key":"195","desc":"195 Maquinas de imprenta"},
                        {"key":"199","desc":"199 Otras"},
                        {"key":"Medios","desc":"Medios de transporte y de manutencion"},
                        {"key":"21","desc":"21 Aparatos de izar:"},
                        {"key":"211","desc":"211 Gruas"},
                        {"key":"212","desc":"212 Ascensores, montacargas"},
                        {"key":"213","desc":"213 Cabrestantes"},
                        {"key":"214","desc":"214 Poleas"},
                        {"key":"219","desc":"219 Otros"},
                        {"key":"22","desc":"22 Medios de transporte por via ferrea:"},
                        {"key":"221","desc":"221 Ferrocarriles interurbanos"},
                        {"key":"222","desc":"222 Equipos de transporte por via ferrea utilizados en las minas, las galerias, las canteras, los establecimientos industriales, los muelles, etc."},
                        {"key":"229","desc":"229 Otros"},
                        {"key":"23","desc":"23 Medios de transporte rodantes, a excepcion de los transportes por via ferrea:"},
                        {"key":"231","desc":"231 Tractores"},
                        {"key":"232","desc":"232 Camiones"},
                        {"key":"233","desc":"233 Carretillas motorizadas"},
                        {"key":"234","desc":"234 Vehiculos motorizados no clasificados bajo otros epigrafes"},
                        {"key":"235","desc":"235 Vehiculos de traccion animal"},
                        {"key":"236","desc":"236 Vehiculos accionados por la fuerza del hombre"},
                        {"key":"239","desc":"239 Otros"},
                        {"key":"24","desc":"24 Medios de transporte por aire"},
                        {"key":"25","desc":"25 Medios de transporte acuatico:"},
                        {"key":"251","desc":"251 Medios de transporte por agua con motor"},
                        {"key":"252","desc":"252 Medios de transporte por agua sin motor"},
                        {"key":"26","desc":"26 Otros medios de transporte:"},
                        {"key":"261","desc":"261 Transportadores aereos por cable"},
                        {"key":"262","desc":"262 Transportadores mecanicos a excepcion de los transportadores aereos por cable"},
                        {"key":"269","desc":"269 Otros"},
                        {"key":"Otros","desc":"Otros aparatos"},
                        {"key":"31","desc":"31 Recipientes de presion:"},
                        {"key":"311","desc":"311 Calderas"},
                        {"key":"312","desc":"312 Recipientes de presion sin fogon"},
                        {"key":"313","desc":"313 Canerias y accesorios de presion"},
                        {"key":"314","desc":"314 Cilindros de gas"},
                        {"key":"315","desc":"315 Cajones de aire comprimido, equipo de buzo"},
                        {"key":"319","desc":"319 Otros"},
                        {"key":"32","desc":"32 Hornos, fogones, estufas:"},
                        {"key":"321","desc":"321 Altos homos"},
                        {"key":"322","desc":"322 Hornos de refineria"},
                        {"key":"323","desc":"323 Otros hornos"},
                        {"key":"324","desc":"324 Estufas"},
                        {"key":"325","desc":"325 Fogones"},
                        {"key":"33","desc":"33 Plantas refrigeradoras"},
                        {"key":"34","desc":"34 Instalaciones electricas, incluidos los motores electricos pero con exclusion de las herramientas electricas manuales:"},
                        {"key":"341","desc":"341 Maquinas giratorias"},
                        {"key":"342","desc":"342 Conductores y cables electricos"},
                        {"key":"343","desc":"343 Transformadores"},
                        {"key":"344","desc":"344 Aparatos de mando y de control"},
                        {"key":"349","desc":"349 Otros"},
                        {"key":"35","desc":"35 Herramientas electricas manuales"},
                        {"key":"36","desc":"36 Herramientas, implementos y utensilios, a excepcion de las herramientas electricas manuales:"},
                        {"key":"361","desc":"361 Herramientas manuales accionadas mecanicamente a excepcion de las herramientas electricas manuales"},
                        {"key":"362","desc":"362 Herramientas manuales no accionadas mecanicamente"},
                        {"key":"369","desc":"369 Otros"},
                        {"key":"37","desc":"37 Escaleras, rampas moviles"},
                        {"key":"38","desc":"38 Andamios"},
                        {"key":"39","desc":"39 Otros aparatos no clasificados bajo otros epigrafes"},
                        {"key":"Materiales","desc":"Materiales, sustancias y radiaciones"},
                        {"key":"41","desc":"41 Explosivos"},
                        {"key":"42","desc":"42 Polvos, gases, liquidos y productos quimicos, a excepcion de los explosivos:"},
                        {"key":"421","desc":"421 Polvos"},
                        {"key":"422","desc":"422 Gases, vapores, humos"},
                        {"key":"423","desc":"423 Liquidos no clasificados bajo otros epigrafes"},
                        {"key":"424","desc":"424 Productos quimicos no clasificados bajo otros epigrafes"},
                        {"key":"429","desc":"429 Otros"},
                        {"key":"43","desc":"43 Fragmentos volantes"},
                        {"key":"44","desc":"44 Radiaciones:"},
                        {"key":"441","desc":"441 Radiaciones ionizantes"},
                        {"key":"449","desc":"449 Radiaciones de otro tipo"},
                        {"key":"49","desc":"49 Otros materiales y sustancias no clasificados bajo otros epigrafes"},
                        {"key":"Ambiente","desc":"Ambiente del trabajo"},
                        {"key":"51","desc":"51 Exterior:"},
                        {"key":"511","desc":"511 Condiciones climaticas."},
                        {"key":"512","desc":"512 Superficies de transito y de trabajo"},
                        {"key":"513","desc":"513 Agua"},
                        {"key":"519","desc":"519 Otros"},
                        {"key":"53","desc":"53 Interior:"},
                        {"key":"521","desc":"521 Pisos"},
                        {"key":"522","desc":"522 Espacios exiguos"},
                        {"key":"523","desc":"523 Escaleras"},
                        {"key":"524","desc":"524 Otras superficies de transito y de trabajo"},
                        {"key":"525","desc":"525 Aberturas en el suelo y en las paredes"},
                        {"key":"526","desc":"526 Factores que crean el ambiente (alumbrado, ventilacion, temperatura, ruidos, etc.)"},
                        {"key":"529","desc":"529 Otros"},
                        {"key":"54","desc":"54 Subterraneos:"},
                        {"key":"531","desc":"531 Techados y revestimientos de galerias, de tuneles, etc."},
                        {"key":"532","desc":"532 Pisos de galerias, de tuneles, etc."},
                        {"key":"533","desc":"533 Frentes de minas, tuneles, etc."},
                        {"key":"534","desc":"534 Pozos de minas"},
                        {"key":"535","desc":"535 Fuego"},
                        {"key":"536","desc":"536 Agua"},
                        {"key":"539","desc":"539 Otros"},
                        {"key":"Otros","desc":"Otros agentes no clasificados bajo otros epigrafes"},
                        {"key":"61","desc":"61 Animales:"},
                        {"key":"611","desc":"611 Animales vivos"},
                        {"key":"612","desc":"612 Productos de animales"},
                        {"key":"69","desc":"69 Otros agentes no clasificados bajo otros epigrafes"},
                        {"key":"Agentes","desc":"Agentes no clasificados por falta de datos suficientes"}
                        ],
                        
                    "table06":[
                        {"key":"1","desc":"REGION CRANEANA (CRANEO, CUERO CABELLUDO)"},
                        {"key":"2","desc":"OJOS (CON INCLUSION DE LOS PARPADOS, LA ORBITA Y EL NERVIO OPTICO) BOCA (CON INCLUSION DE LABIOS, DIENTES Y LENGUA)"},
                        {"key":"3","desc":"CARA (UBICACION NO CLASIFICADA EN OTRO EPIGRAFE)"},
                        {"key":"4","desc":"NARIZ Y SENOS PARANASALES"},
                        {"key":"5","desc":"APARATO AUDITIVO"},
                        {"key":"6","desc":"CABEZA, UBICACIONES MULTIPLES"},
                        {"key":"7","desc":"CUELLO"},
                        {"key":"8","desc":"REGION CERVICAL"},
                        {"key":"9","desc":"REGION DORSAL"},
                        {"key":"10","desc":"REGION LUMBOSACRA (COLUMNA VERTEBRAL Y MUSCULAR ADYACENTES) TORAX (COSTILLAS, ESTERNON)"},
                        {"key":"11","desc":"ABDOMEN (PARED ABDOMINAL)"},
                        {"key":"12","desc":"PELVIS"},
                        {"key":"13","desc":"TRONCO, UBICACIONES MULTIPLES"},
                        {"key":"14","desc":"HOMBRO (INCLUSION DE CLAVICULAS, OMOPLATO Y AXILA)"},
                        {"key":"15","desc":"BRAZO"},
                        {"key":"16","desc":"CODO"},
                        {"key":"17","desc":"ANTEBRAZO"},
                        {"key":"18","desc":"MUNECA"},
                        {"key":"19","desc":"MANO (CON EXCEPCION DE LOS DEDOS SOLOS)"},
                        {"key":"20","desc":"DEDOS DE LA MANO"},
                        {"key":"21","desc":"MIEMBRO SUPERIOR, UBICACIONES MULTIPLES"},
                        {"key":"22","desc":"CADERA"},
                        {"key":"23","desc":"MUSLO"},
                        {"key":"24","desc":"RODILLA"},
                        {"key":"25","desc":"PIERNA"},
                        {"key":"26","desc":"TOBILLO"},
                        {"key":"27","desc":"PIE (CON EXCEPCION DE LOS DEDOS)"},
                        {"key":"28","desc":"DEDOS DE LOS PIES"},
                        {"key":"29","desc":"MIEMBRO INFERIOR, UBICACIONES MULTIPLES"},
                        {"key":"30","desc":"APARATO CARDIOVASCULAR EN GENERAL"},
                        {"key":"31","desc":"APARATO RESPIRATORIO EN GENERAL"},
                        {"key":"32","desc":"APARATO DIGESTIVO EN GENERAL"},
                        {"key":"33","desc":"SISTEMA NERVIOSO EN GENERAL"},
                        {"key":"34","desc":"MAMAS"},
                        {"key":"35","desc":"APARATO GENITAL EN GENERAL"},
                        {"key":"36","desc":"APARATO URINARIO EN GENERAL"},
                        {"key":"37","desc":"SISTEMA HEMATOPOYETICO EN GENERAL"},
                        {"key":"38","desc":"SISTEMA ENDOCRINO EN GENERAL"},
                        {"key":"39","desc":"PIE (SOLO AFECCIONES DERMICAS)"},
                        {"key":"40","desc":"APARATO PSIQUICO EN GENERAL"},
                        {"key":"41","desc":"UBICACIONES MULTIPLES, COMPROMISO DE DOS O MAS ZONAS AFECTADAS ESPECIFICADAS EN LA TABLA"},
                        {"key":"42","desc":" ORGANO, APARATO O SISTEMA AFECTADO POR SUSTANCIAS QUIMICAS - PLAGUICIDAS"},
                        {"key":"43","desc":"OTROS"}
                        ],
                    "table07":[
                        {"key":"1","desc":"ESCORIACIONES"},
                        {"key":"2","desc":"HERIDAS PUNZANTES"},
                        {"key":"3","desc":"HERIDAS CORTANTES"},
                        {"key":"4","desc":"HERIDAS CONTUSAS (POR GOLPES O DE BORDES IRREGULAR)"},
                        {"key":"5","desc":"HERIDA DE BALA"},
                        {"key":"6","desc":"HERIDA DE TEJIDOS"},
                        {"key":"7","desc":"CONTUSIONES"},
                        {"key":"8","desc":"TRAUMATISMOS INTERNOS"},
                        {"key":"9","desc":"TORCEDURAS Y ESGUINCES"},
                        {"key":"10","desc":"LUXACIONES"},
                        {"key":"11","desc":"FRACTURAS"},
                        {"key":"12","desc":"AMPUTACIONES"},
                        {"key":"13","desc":"GANGRENAS"},
                        {"key":"14","desc":"QUEMADURAS"},
                        {"key":"15","desc":"CUERPO EXTRAÑO EN OJOS"},
                        {"key":"16","desc":"ENUCREACION (PERDIDA OCULAR)"},
                        {"key":"17","desc":"INTOXICACIONES"},
                        {"key":"18","desc":"INTOXICACIONES POR PLAGUICIDAS"},
                        {"key":"19","desc":"ASFIXIA"},
                        {"key":"20","desc":"EFECTOS DE ELECTRICIDAD"},
                        {"key":"21","desc":"EFECTOS DE LAS RADIACIONES"},
                        {"key":"22","desc":"DISFUNCIONES ORGONICAS"},
                        {"key":"0","desc":"OTROS"}
                        ],
                        
                    "table08":[
                        {"key":"1","desc":"ENFERMEDADES PROFESIONALES CAUSADAS POR AGENTES QUIMICOS"},
                        {"key":"2","desc":"ENFERMEDADES PROFESIONALES CAUSADAS POR AGENTES FISICOS"},
                        {"key":"3","desc":"ENFERMEDADES PROFESIONALES CAUSADAS POR AGENTES BIOLOGICOS"},
                        {"key":"4","desc":"ENFERMEDADES PROFESIONALES CAUSADAS POR INHALACION DE SUSTANCIAS Y AGENTES NO COMPRENDIDAS EN OTROS APARTADOS"},
                        {"key":"5","desc":"ENFERMEDADES PROFESIONALES DE LA PIEL CAUSADAS POR SUSTANCIAS Y AGENTES NO COMPRENDIDOS EN ALGUNO DE LOS OTROS APARTADOS"},
                        {"key":"6","desc":"ENFERMEDADES PROFESIONALES CAUSADAS POR AGENTES CARCINOGENICOS"},
                        {"key":"7","desc":"OTRAS"}
                        ],
                        
                    "table09":[
                        {"key":"1","desc":"ATRAPAMIENTO SIN DAÑO (DENTRO, FUERA, ENTRE, DEBAJO)"},
                        {"key":"2","desc":"CAIDA DE UN ASCENSOR"},
                        {"key":"3","desc":"CAIDAS DE CABLES DE ALTA TENSION - CONTACTO DE MAQUINARIAS O PARTE DE ELLAS CON CABLES DE ALTA TENSION"},
                        {"key":"4","desc":"CAIDAS DE CARGAS IZADAS (CONTENEDORES, PAQUETES DESCARGAS, ETC)"},
                        {"key":"5","desc":"CHOQUE DE VEHICULOS DE TRABAJO"},
                        {"key":"6","desc":"DERRAME, ESCAPES, FUGAS DE MATERIALES PELIGROSOS (Corrrosivos, Reactivos, Explosivos, Toxicos, Inflamable, Biologicos patogenos)"},
                        {"key":"7","desc":"DERRUMBE DE UNA CONSTRUCCION"},
                        {"key":"8","desc":"DERRUMBE DE UNA MINA"},
                        {"key":"9","desc":"DERRUMBES (ZANJAS, TALUDES, CALZADURAS,EXCAVACIONES,DE TERRENOS EN GENERAL, ETC)"},
                        {"key":"10","desc":"DESASTRES DE ORIGEN ANTROPOGENICO (AEREO, MARITIMO)"},
                        {"key":"11","desc":"DESASTRES DE ORIGEN NATURAL (SISMOS, FLUVIALES, PLUVIALES, TERRESTRE)"},
                        {"key":"12","desc":"DESPLOMES ESTRUCTURAS, INSTALACIONES, PRODUCTOS ALMACENADOS"},
                        {"key":"13","desc":"DESPRENDIMIENTO DE ROCAS"},
                        {"key":"14","desc":"EPIDEMIAS /INTOXICACIONES MASIVAS"},
                        {"key":"15","desc":"EXPLOSIONES"},
                        {"key":"16","desc":"INCENDIOS"},
                        {"key":"17","desc":"INCURSIONES TERRORISTAS/ATENTADOS/SABOTAJES"},
                        {"key":"18","desc":"SITUACIONES DE CONMOCION CIVIL / MOTINES"},
                        {"key":"19","desc":"TORMENTAS ELECTRICAS INUSUALES"},
                        {"key":"20","desc":"VOLCADURA CON EXPLOSIVOS SIN PREVIO AVISO"},
                        {"key":"21","desc":"VOLCADURA DE BOTELLAS PRESURIZADAS"},
                        {"key":"22","desc":"OTROS"}
                        ],
                        
                    "user":[
                        {"name":"Luis Alberto","cargo":"Admin"},
                        {"name":"Juan Carlos","cargo":"Admin"},
                        {"name":"Miguel Ángel","cargo":"Supervisor"},
                        {"name":"Carlos Alberto","cargo":"Supervisor"},
                        {"name":"María Pilar","cargo":"Admin"},
                        {"name":"María Isabel","cargo":"Supervisor"},
                        {"name":"Rosa María","cargo":"Supervisor"}
                    ],
                    // "table01":
                };
                var oModel = new sap.ui.model.json.JSONModel(oData);
                this.setModel(oModel);
                this.setModel(oModel, "myParam"); 
            }
        });
    }
);